disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "J.Mwangi Cybersecurity"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/bnslogo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "An informative oasis , full of cyber security lab walktrough!"
  copyright = "&copy; 2025 James Mwangi K" 

 [params.author]
   name = "James Mwangi K"
   email = "jamesmwang1@proton.me"
   image = "img/bnslogo.png"
   imageQuality = 96
  headline = ''' "First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack."
   - -George Carrette'''
  bio = "_Jamesh_ is a master applied mathematician with a passion for simplifying complex concepts. He brings onboard a background in creating mathematical algorithms and creativity to Cybersecurity projects. His approach helps individuals navigate technology adoption and Cybersecurity easily.  In his free time, he reads and listen to good music "
  links = [
     { email = "jamesmwang1@proton.me" },
     { github = "https://github.com/jameshmwangi" },
     { linkedin = "https://www.linkedin.com/jamesh-mwangi" },     
     { twitter = "https://twitter.com/jameshqater" },
     { x-twitter = "https://twitter.com/jameshqater" },
     { ko-fi = "https://ko-fi.com/jamesmwangi59" },

   ]
